name:                drasil-sysinfo
version:             0.1.0.0
github:              "github.com/JacquesCarette/Drasil"
license:             BSD3
author:              "Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette, Spencer Smith"
copyright:           "2021 Jacques Carette, Spencer Smith"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- drasil-database
- drasil-lang
- drasil-theory

library:
  source-dirs: lib
  exposed-modules:
  - Temp.Drasil.SystemInformation
  - Temp.Drasil.GetChunk
